### ISSUE TITLE
Whitepaper Feedback: part 1

### ISSUE THREAD

**Issue by burrrata** [Joystream/whitepaper#12]
Hey guys! Awesome ideas :)

I read through the paper on and off as I wandered around today so some of my questions/comments are more coherent than others lol. I created these notes as I read, so while some things might be addressed later in the paper, the notes are from the perspective of someone reading through start to finish. Hopefully this will help with the organization of ideas. A lot of other suggestions are just english grammar/copy things, but hopefully they help make the paper more accessible to a broader audience. I only got halfway through the paper today, but had lots to say so I figured it probably wouldn't hurt to share in chunks as I go. Hope this is helpful and I'm really stoked to see this project evolve.

Also, if I had 1 piece of advice from all of my notes though, it would be this: If at all possible, do not create new terminology. New terminology creates immediate cognitive overhead for the reader, and ongoing cognitive friction as they try to understand a new concept in a new context. To make it easier, keep things as simple as possible.

-  As often as possible reuse common ideas and terms from the blockchain space or other disciplines.
- If you have to create new terminology, try to only present 1 new concept at a time. This might look like presenting new ideas on their own first and then in a separate section presenting how they interact with each other. That way the reader can process the newness of the concept and the newness of the concept doing stuff with other things as separate events, and thus allocate more brainpower to each.  
- When you're explaining that new terminology explain it as clearly as possible. That way your worst case scenario is that the reader thinks you talk a lot vs the worst case scenario being that they just don't get it. Also, make sure the names of terms are distinctly different from one another so that they don't get confused in the readers head. Clear distinctions and clear explanations can go a long way. 

# Feedback On Sections 1 - 11

### Page 5, Section 3: Notes, 3rd paragraph:

- says: "...hard for or consensus upgrade"
- did you mean: "...hard **fork** or consensus upgrade"

### Page 3, Section 4: Blockchain, 1st paragraph:

- says: "...a silten transaction ordering mechanism..."
- TBH I'm not exactly sure what that means. Did you mean a "...**black box** transaction ordering mechanism...": meaning that the transaction ordering mechanism is assumed to work, but we don't look at the internals of that process (thus the "black" part of "black box")?

### Page 3, Section 4: Blockchain, 1st paragraph, last sentence:

- says: "This would be *as* distinct from the state..."
- did you mean: "This would be distinct from the state..." (removing the as)

### Page 6, Section 4.1: Consensus - Light client friendly, 2nd paragraph, 1st sentence:

- says: "In these algorithms, a light client only needs to track any potential changes in the validator set, which in practice will change quite infrequently, for example due to the unbonding period induced delay, and not in large increments."
- might want to say something like: "In these algorithms, a light client only needs to track any potential changes in the validator set, which is assumed to change only in small increments (why?), and if it does, to do so quite infrequently due to the delay induced by the unbonding period."
- also, why would the validator set only change in small increments?

### Page 7, Section 4.2, Upgrading: genuine accountability

Really appreciate how you guys are thinking about ways to facilitate signalling along with the actual voting process. This seems really essential for coordination, esp with distributed decentralized communities :)

### Page 8, Section 4.3: Asynchronous Transaction Processing, 1st paragraph:

- general comment: overall I think I understood the principle: that a tx that needs time to confirm will be locked until that time has passed (like how Rust locks variables in concurrent threading). That being said, it took me a few reads to get there.
- this sentence was especially confusing for me: "Now during this locking period, which typically will last for a predefined number of blocks, the validator nodes are free to conduct the desired processing for the initial transaction outside of the normal sequential validation of blocks, for example on a separate processing unit."

### Page 8, Section 4.4.1: Models: BRAQ, 1st paragraph, last sentence:

- says: "Successfully issuing such transactions within the given limits do not involve marginal outlay for the given actor."
- did you mean: "Successfully issuing such transactions within the given limits will not incur additional fees for the actor."

### Page 8, Section 4.4.1: Models: BRAQ, 2nd paragraph:

- says: "Given that BRAQ will cover the majority of transactions, security would be primarily be financed through minting tokens, which also more closely matches the public goods nature of chain security."
- I'm confused: how will minting tokens create security? Are you implying that tokens will be minted as a block reward to incentivize people to stake and validate the chain? Also, if you're a parachain on the Polkadot network, will this just roll over to Polkadot or are you going to have your own "pre-consensus" process before being finalized by Polkadot validators? 

Also, just below that the way you describe on-boarding is awesome! I'd love to see that expanded more (maybe you do in the rest of the paper, but I'm just writing as I go). Low friction onboarding without exchanges is a **HUGE** thing that more projects need :)

### Page 8, Section 4.4.1: Models: BRAQ, last paragraph:

- says: "Secondly, this approach explicitly subjects the fee model to a dynamic governance process, where all default limits, and individual member quotas, can be adjusted. This is an easy, and possible the only feasible, long term mechanism for correcting the externalities associated with long term social cost of transaction processing and state utilization in public chains."
- did you mean: "Secondly, this approach explicitly subjects the fee model to a dynamic governance process, where all default limits, and individual member quotas (what?), can be adjusted. This aims to create a mechanism for correcting the long-term externalities associated with the social cost of transaction processing and state utilization in public chains. (this sentence is heavy, yet vague)"

What are "individual member quotas"? I don't think that was addressed. 

When you say: "This aims to create a mechanism for correcting the long-term externalities associated with the social cost of transaction processing and state utilization in public chains." that's very hard to read and also vague (even though it's technically correct). Is there another way you could phrase that so that it's more descriptive and user friendly?

### Page 9, Section 4.4.2: BRAQ, last paragraph:

I didn't get it. 

- what do you mean when you say: "share a quota across a range of instances?". What are these instances? 
- what are "custom quotas", who decides them, and how can they be changed?
- the last sentence completely left me lost: to make the paper more user friendly, explain the concepts here in more detail and give them more context.  

### Page 10, Section 4.5: Interoperability, 2nd paragraph, 2nd sentence:

- says: "For each blockchain which needs to be integrated with Joystream, deploy a light client instance on each side, for the opposite side, where there is a requirement to write to the state on of the first."
- the first half of the sentence makes sense, but I have no idea what the second half is supposed to mean

Otherwise the paragraph and section makes sense :) but just that one sentence didn't read clearly. 

### Page 10, Section 5: Accounts and Tokens, 2nd paragraph, 1st sentence:

- says: "New tokens are minted continuously for a very wide range of purpose, all primarily to reward some actor for some behavior."
- did you mean: "New tokens are minted continuously for a very wide range of **purposes**, all primarily to reward some actor for some behavior."

### Page 10, Section 5: Accounts and Tokens, 2nd paragraph, last sentence:

- says: "As a result of these three separate exogenous dynamics - and the platform upgradeability functionality, there is no ex-ante certainty about the total supply of the token at different points in time in the future."
 - did you mean:  "As a result of these dynamics (minting and burning) as well as the platform upgradeability functionality, there is no certainty about the total supply of the token at different points in time in the blockchain's lifetime."

### Page 10, Section 5: Accounts and Tokens, 3rd paragraph, 1st sentence:

- says: "The other tokens are related to the content finance market, described further in section \ref{sec:content_finance}."
- the term "content finance market" is vague and boring. Maybe name it something more exciting and specific?

### Page 10, Section 5: Accounts and Tokens, 3rd paragraph, more stuff:

Maybe add a few more sentences to explain that process and what exactly you mean here:
- says: "The registration of a key in the balances of a token is referred to as an \textit{account}."
- are you trying to say that when a user creates a key that holds a balance, that pair is considered an "account"? If so, that makes sense from the technical standpoint of a key/value pair mapping where the key is a pub/priv ECC pair like ed25519 or whatever. That's not immediately obvious though (if that's even what you're referring to here).
- or is this more like a Plama Cash model where a key is correlated to a tokens place in a state and the key (access to ownership of the token) is what moves around?

Also:
- says: "Normal spending operations can be conducted from an account to any new, or existing, account on the same token, by being able to sign a message with a private key that matches the public key corresponding to the origin account."
- what do you mean when you say "on the same token"? Do you mean transferring the token, or that each token has it's own "state" as a subset of the state of the JoyStream blockchain, and that "token state has it's own set of accounts and keys separate from other "token states" on the JoyStream blockchain?

Also:
- says: "The token registry is a mapping from a \textit{token identifier}, which is a unique positive integer, to the corresponding token profile."
- the "token registry" is just a list that manages all of the tokens on the JoyStream platform right?

Anyways, with all this a user can have a single account identity on the JoyStream blockchain that holds multiple JoyStream tokens right? (even though you explain that it's technically not like an Etheruem account can have mutliple ERC-20 tokens, from an end user perspective it's all within the same wallet UI that's accessed via a single key right?)

### Page 11, Section 6: Member:

How will this be interoperable with other identification mechanisms on the Polkadot network? Would you just create an API that allows people to link various identity solutions and have them connect/control an account on JoyStream?

 
### Page 12, Section 6.2: Member Profile and Registry, last paragraph:

- says: "Once a membership has been established, it is permanent."
- How will this deal with people registering someone else's name? For example, if someone registers JoyStreamSupport as a member identifier and then uses it for fraudulent activity, or similarly registers another person's name and then impersonates them. How would this be addressed, and how would the rightful owner of a public name/brand acquire that membership ID? 
- Also, what if someone registers the top 1000 brands or something, or 1000 variations on a popular identity? From a financial perspective this could still be profitable to an attacker, despite the fees deterring regular users. How would this be addressed?

Also
- it says: "For a given key, there may both a corresponding account and membership, or either one exclusively. While an actor may find it practical to identify with the same key in both capacities, the system cannot, and does not, enforce this."
- that sounds like an important point to clarify because it could confuse people trying to understand how the system works. Anytime you add new platform specific terms, esp those like "membership" and "account" that are often used synonymously on legacy platforms, it's important to be unfailingly explicit as to what they are and what they are referring to. Maybe even come up with a way to clearly distinguish between the two so that people don't get confused. 

### Page 13, Section 6.4: Subscription, general:

- Is this a built in way for an account to subscribe to being part of a service (like Netflix or Patreon or whatnot)?
- Or is this a subscription to actually be a member on the platform (see I'm already getting confused on the separation between member and account lol)

### Page 14, Section 7: Roles Staking Slashing:

I'm very hungry (low blood sugar) so maybe this is extra hard for me to comprehend atm, but if you're going to add additional terms like "roles" the already vague term of "membership" that is somehow distinctly separate from "accounts" then you have to be **very very clear** about what those differences are and why they matter. Atm I read it and it kind of sort of makes sense, but not in any way that is meaningful to me. What are these terms and why do they matter? What might they be used for? 

- Maybe include diagrams and things? 
- Or a whole section in the beginning that explains the different ways a person can engage with JoyStream, what they're called, and why they matter. That way when you refer to "accounts", "members", "roles", etc  in the rest of the paper people will already have a reference point as to what those things are. Much easier than trying to understand a new concept as well as how it interacts with other new concepts all in the same place. First the concepts. Then how they all interact. Hope that makes sense. If not happy to try to clarify though :)

### Page 14, Section 8: Rewards:

It says: "All staking is \textit{rewarded} in tokens paid out directly to the member account, and if no account exists, the membership key will be used to credit an account with the same key."
- What does that mean? How can you stake without having an account?

Also, is this section trying to describe staking mechanisms in general, or will **all** staking on JoyStream be required to follow this formula? 

### Page 14, Section 9.1.1: Terms:

it says: "Proposals are bids to execute given operations on the platform state in order to serve some contemplated end."
- maybe drop the the word "contemplated". It just sounds pretentious and doesn't really add any information

### Page 14, Section 9.2: Elections:

It sounds like you're really trying to explain a liquid democracy where people can delegate their votes? If so, I'd recommend using terms that people are already familiar with rather than "backing". Is there any difference between this process and just general voting that requires that it use a different term? 

Also, having a manual reveal process creates friction for users and will reduce participation. Is there a specific reason why you guys chose that method here?

Also, why do people have to lock their tokens while they "back" a council member? Would these be the same tokens that people use for other functions on the platform, and if so, wouldn't that create an opportunity cost to voting where you have to give up the ability to do other things on the network just to back someone? 

Grace Stage
- says: "This is so all properly new stake should be able to exit the consequences of an unfavourable council."
- did you mean: "This provides a method to exit if a voter does not support the new council."

### Page 16, Section 9.1.3: Rewards:

- how/why do voters receive a payout?
- why would the council payout be proportional to the voter turnout? If the platform is successful this create **huge** incentives for council members to manipulate terms to retain power. This could be bribery, sybil attacks, etc... all of which fall under the larger off-chain game of life despite that they might be sound in the smaller game of the on-chain protocol (like I mentioned in the memberID section).

### 9.2 Proposals

The term "constitutionality" is really just "finality" in the blockchain consensus world. Since most people are already familiar with that, and people exploring the protocol will read that finality is linked to the amount of blocks that have passed, why create a new term? Is there any reason the term "finality" couldn't be used here?

### 9.2.2 Life Cycle

Why have a commit/reveal process? Wouldn't it be easier for all parties involved to just use some kind of zero knowledge system where people can vote, and verify that they voted, but without revealing any information about that vote until the voting is done? Then you could automate the whole thing, reducing friction that might deter participation and reducing the resources required to participate (time).

Also, the "slash" option seems like it could be abused. What if over time the community becomes divided (like many political parties become), and as one group gains power they slash the controversial proposals of the other group, but the other group can't leave because if they do they'll lose their tokens on the original network and the new network will be susceptible to market pressures and most likely fail (potentially by attack from the original network). Are there conditions on this to prevent abuse? 

- potentially requiring a super majority (80/20) to slash
- or maybe saying that slashing can only take a portion of the stake rather than the whole thing so it's more like a slap on the wrist than a beating

  

 ### 10: Membership Screening and Curation

This is one of the coolest and most important parts of the paper so far. It addresses 2 problems:

- the user onboarding problem: you want it to be easy and fast for people to discover, use, and contribute to the network 
- and the freeloader problem: you don't want people to quickly discover, abuse, and ruin the network

As you're probably aware, there's been a lot of research that's gone into this in various p2p networks, and luckily because lots of torrenting and streaming services have been running for years, there's actual data to look at :) Reminded me of this article I came across that you might appreciate: https://medium.com/@jbackus/private-bittorrent-trackers-are-markets-1d3cc3c9bacd

As you addressed, with a dynamic community driven network the resources that can be used are more than just compute and bandwidth, but also peer member attention. With the method you propose, do users have a "reputation weight" where they can on board users or vouch for them relative to their weight in the community? If so, how would one build reputation? 

- For example, if I get on-boarded by a leader of the community does that have more weight than someone who was on boarded yesterday?
- What if you on board me, and I on board Bob, and Bob onboards Alice, and Alice on boards Eve and Eve is evil. Will that only hurt Alice, or will we all suffer? 
- Also, this scenario makes me think of Trustlines where one user would extend "credit" to another and then create community currency networks. If the asset being extended is "repuation" instead of currency, then it could help with organic community growth. It's the original idea Ripple was founded on. If you're interested, here's the white paper and GitHub, although the project has been abandoned due to leadership disputes with the company who was funding it :/ Their code is still available though and they had a functioning DApp on the Ethereum testnet! There's also various videos of them explaining the project on YouTube. It was really cool. My favorite idea in the entire Ethereum space actually :)

 - https://github.com/trustlines-network/trustlines-network.github.io/blob/master/whitepaper_v03.pdf

### 10.1 Typos/Questions

paragraph 1, sentence 3:

- change "consumer" to "consume"
- the last 2 sentences in the first paragraph don't make sense: what did you mean here? How are payouts shaped?

### 10.3 Screening

This part doesn't quite sit well with me. 

- Email and social media can be hacked and spoofed, and creating a reliance on centralized intermediaries filters out people like me who only use Reddit as social media. Imagine if I was part of other developer circles, but didn't use the mainstream applications that you use for on boarding. That would suck :/
- CAPTCHAs almost all have trackers built in (last time I checked)
- Onboarding delays cause friction in the on boarding process and piss off users. I'm not going to be able to get my friends to join unless it's easy. 
- Manual human confirmation doesn't scale :/

Barry Whitehat in the Ethereum research forum had some great ideas around anonymous reputation and identity management though. If you wanted to skip the zk proof setup (and computation), then you could just have a system where in every epoch if a certain amount of users signal that an account is being malicious (or not contributing in any way), then that account is removed. There could also be a "holding period" where the account is simply frozen and the account owner can make an appeal. Not perfect because it still requires a validator set to look at appeals and could also be subject to sybil attacks if too many users are malicious, but as long as most people are honest it could be a direction to explore. (note: I'm not proposing this as a solution, but a direction to explore that could lead towards a solution) 

- https://ethresear.ch/t/anonymous-reputation-risking-and-burning/3926

Also, the "Text" portion of the user agreement (really just a Terms of Service) is agreed upon and created by the community so that it's not crazy and over reaching like the current Terms of Service on many sites right? 

### 11 Data Storage and Distribution

So... if the network is public, that means that anyone can download and store it at any time, which means that someone can just wait around until quantum computers are viable, then use that to crack the encryption, and then act (potentially retroactively) on that data. For an example, just look at all the people who used Monero before it got upgraded and who's tx are now being analyzed. You're thinking about quantum secure encryption right? 

Also, in this section the subscription idea was brought up again, but this time in the context of streaming data. **Now** it makes more sense, but before there wasn't the context of streaming data. If that's one of the main goals/features of the platform, maybe say that up front in the intro? 

Regarding "Ad Awareness": what if users created a profile explicitly saying what types of ads they want to see and then either exchanged ads for content, or were paid to watch if the content provider paid the bill up front (then you get into a net neutrality debate though lol)? Kind of like how Brave does it? Would there be any benefit to integrating Brave directly? You could potentially access their base of advertisers who are already signed onto that platform if you had a revenue sharing agreement that would be enforced via a protocol? Just thinking out loud here lol

Regarding the game theoretic mechanisms that will align interests of buyers and sellers of bandwidth,  the article I mentioned earlier on torrents might be of interest

- https://medium.com/@jbackus/private-bittorrent-trackers-are-markets-1d3cc3c9bacd

**Comment by bedeho** [comment]
Hi, I only _randomly_ saw this now, very we did not respond when you posted, didn't get any notification, you clearly put a lot of work into this.
